### ISSUE TITLE
Housekeeping for URLs...

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-codespace#1]
Assuming it's cool with @rbeezer, can you transfer this repo to @PreTeXtBook?

Also, slight preference, can we call this `pretext-template` instead?

**Comment by rbeezer** [comment]
Your work can certainly live at @PreTeXtBook.  @davidfarmer  should be consulted also.

But I am also negative on proliferation of repositories.  Newcomers do not understand what lives where.  I could cite examples.  ;-)   is there a good reason this **needs** to be independent?

**Comment by oscarlevin** [comment]
The idea with this repository is that it is a starter template that new users can, with two clicks, create a new repo all set up to run pretext in codespaces.  As such this cannot be part of another repository.

I don't have a strong preference on the name.  Pretext-template or pretext-gh-template or pretext-online-template?

**Comment by StevenClontz** [comment]
Since technically this infrastructure does not only work online, maybe `pretext-codespace`?

**Comment by StevenClontz** [comment]
I'm talking myself out of `pretext-template` since it's not actually a "PreTeXt template", it's a "template repository" used to set up our recommended Codespace.

**Comment by rbeezer** [comment]
> this cannot be part of another repository

OK, just running my filters.  Contact @davidfarmer if you need help setting up on @PreTeXtBook.

**Comment by davidfarmer** [comment]
Shall I clone this into the PreTeXtBook organization and then math Steven and Oscar Owners?

**Comment by oscarlevin** [comment]
That would be fine, or I can transfer the repository.  When I get back from break.

**Comment by oscarlevin** [comment]
Actually, seems like I was able to transfer on my phone.  So we should be set now.  I went with `pretext-codespace`

**Comment by StevenClontz** [comment]
Beautiful!
