### ISSUE TITLE
Rebuild Docker images

### ISSUE THREAD

**Issue by bjones1** [PreTeXtBook/pretext-codespace#11]
Currently, the PreTeXt codespace installs an old version of the CodeChat Server, which causes it to fail in Codespaces. Would you rebuild the three Docker images in https://github.com/oscarlevin/pretext-docker so the CodeChat Server will be updated?

**Comment by oscarlevin** [comment]
This should be done now, and I've set up an action that will rebuild them weekly and on demand.
